### ISSUE TITLE
css 水平垂直居中总结

### ISSUE THREAD

**Issue by jerryni** [jerryni/fe-study-notes#10]
## 水平居中

对于inline和inline-*(inline-block, inline-table, inline-flex)元素:
> text-align: center;

如果是一个block级元素:
> 则使用margin: 0 auto;

如果是多个block级元素:

- 可以考虑在外层加上inline-block级元素，再利用1中方法
- 也可考虑在外层加上flex-box级元素。再使用`justify-content: center`

### 如果是inline和inline-*元素

- 最常用的做法是利用line-height, 让height等于line-height
- 还可利用父元素，设置其上下padding相等。
- 其中img元素还可以利用vertical-align: center;

### 如果是block级元素 

- 高度已知 
利用绝对定位和负margin。top:50%,margin-top设置为(负)子元素高度（`box-sizing: content-box, H = height + padding`）的一半。

- 高度未知 
仍然是利用绝对定位。由于高度未知，使用transform: translateY(-50%);
使用flexbox 
对父元素使用如下代码: 
```css
.parent {
    display: flex;
    flex-direction: column;
    justify-content: center;
}
```

### 定宽和定高

- 和上文的垂直居中一样，可以利用绝对定位+负margin。为了水平居中，还得加上left和margin-left。

- 绝对居中:
```css
.Absolute-Center {
      margin: auto;
      position: absolute;
      top: 0; left: 0; bottom: 0; right: 0;
      height: a value;
      width: a value;
}
```
注释：
- 在正常文档流里，margin: auto;意味着margin-top和margin-bottom等于0。
- 使用绝对定位意味着脱离了正常文档流
- 使用`top: 0; left: 0; bottom: 0; right: 0;`来定位。对于绝对定位元素，这些值意味着此元素的margin与其包含块边缘是紧贴着的。
给定height和width,浏览器才能据此渲染margin值。因为绝对定位脱离了文档流，margin-top和margin-bottom便不再是0，而会是相等的值。
> This property specifies how far an absolutely positioned box’s top margin edge is offset below the top edge of the box’s containing block.

### 不定宽高

- 也与上文一致，但使用transform: translate(-50%,-50%)。
- 使用flex-box(不适合fix/absolute) 
```css 
.parent { 
    display: flex; 
    align-items: center; 
    justify-content: center; 
}
```

- 利用table(不适合绝对定位/fixed时使用)
父元素:
```css
.parent {
    display: table; 
    width: 100%; 
}
```
子元素设置为:
```css
.child {
    display: table-cell;
    vertical-align: middle;
    text-align: center;
}
```

## 文字竖排的垂直水平居中

- `line-height` 影响文字水平宽度
- `height, text-align` 影响文字垂直高度, 居中方式

```css
.container {
    position: absolute;
    left: 0;
    top: 0;
    width: 50px;
    height: 100%;

    text-align: center; /*垂直居中*/
    
    .coupon-title {
        line-height: 50px; /*水平居中*/
        height: 100%; /*垂直居中*/
        /*font-size: .7rem;*/
        /*letter-spacing: .1rem;*/
        -webkit-writing-mode: vertical-rl;
    }
}
```
### 参考资料

http://codepen.io/shshaw/full/gEiDt
https://css-tricks.com/centering-css-complete-guide/
https://css-tricks.com/centering-in-the-unknown/
