### ISSUE TITLE
 iOS Retina 屏，设置 1px 边框，实际显示 2px 解决方案

### ISSUE THREAD

**Issue by jerryni** [jerryni/fe-study-notes#2]
http://jinlong.github.io/2015/05/24/css-retina-hairlines/

最后的解决方式:

- 绝对定位的伪类after或before
- 高度为1px
- transform: scaleY(0.5)或 scalseX(0.5) 按照实际情况而定
- 最后通过`devicePixelRatio >= 2` 判断retina分辨率 是否加类

```css
.hairlines li{
    position: relative;
    border:none;
}
.hairlines li:after{
    content: '';
    position: absolute;
    left: 0;
    background: #000;
    width: 100%;
    height: 1px;
    -webkit-transform: scaleY(0.5);
            transform: scaleY(0.5);
    -webkit-transform-origin: 0 0;
            transform-origin: 0 0;
}
```

```js
if(window.devicePixelRatio && devicePixelRatio >= 2){
    document.querySelector('ul').className = 'hairlines';
}
```
